---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/settings

title: {{HOMEPAGE_VAR_TITLE}}

background: https://images.pexels.com/photos/933054/pexels-photo-933054.jpeg
theme: dark
cardBlur: md

headerStyle: {{HOMEPAGE_VAR_HEADER_STYLE}}

layout:
  Media:
    style: row
    columns: 3
  Download:
    style: row
    columns: 3
  Networking:
    style: column
    columns: 1

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true